<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My first page</title>
</head>
<body>
    <h1>This is my first page</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vel quidem excepturi, dolores repellat perspiciatis dolore ex ratione molestiae totam, itaque cum officiis natus optio, obcaecati cupiditate culpa expedita est facilis.</p>
    <p><a href="/users">List of users</a></p>
</body>
</html>